dir_rule:
  base_dir: E:/18comic_down/books
  rule: Bd_Aid

client:
  proxies:
    http: "socks5://127.0.0.1:7890"
    https: "socks5://127.0.0.1:7890"
  retry_times: 5
  timeout:
    connect: 30
    read: 60

download:
  cache: true  
  image:
    decode: true 
    suffix: .jpg
  threading:
    batch_count: 20
    delay:
      min: 1.0
      max: 3.0